### ISSUE TITLE
Rename to "error-page" and implement status code links

### ISSUE THREAD

**Issue by FRickReich** [ShipyardSuite/not-found#2]
Currently, when any service leads to a page does not exist, this service shows an error page for status 404, it would be better if this service shows up a page based on status codes, by linking to errorPage/404, errorPage/500 and so on.

**Todo:**
- [ ] Implement status code dependent pages
- [ ] Rename Repository and service to error-page or just error
- [ ] Add documentation for this service in its Wiki and its README.md file

**Note:**
I think this could be a good little practice to work with docker, react and microservice environment and understand its workflow a bit better.
